config/routes.rb
Loto::Application.routes.draw do

  root :to => "clients#index"

  resources :clients do
    resources :forms do
      resources :authemps
      resources :procedures
    end
  end

end

app/models/authemp.rb
class Authemp < ActiveRecord::Base
  belongs_to :form
  attr_accessible :name, :title
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :contact, :details, :location, :name
  has_many :forms, :dependent => :destroy
end

app/models/form.rb
class Form < ActiveRecord::Base
  belongs_to :client
  has_many :procedures, :dependent => :destroy
  has_many :authemps, :dependent => :destroy
  attr_accessible :assessor, :chem_hazmat, :assess_date, :elec_highvolt, :elec_lowvolt, :equip_id, :equip_location, :equip_name, :ion_rad, :mech, :non_rad_rf, :non_rad_uv, :other, :other_text, :press_hyd, :press_pneu, :stored_engy, :tasks_performed, :therm_cryo, :therm_high, :vacuum, :procedures_attributes, :authemps_attributes, :highvolt_text, :lowvolt_text, :hazmat_text, :mech_text, :stored_text, :cryo_text, :high_text, :hyd_text, :pneu_text, :vac_text, :rad_text, :uv_text, :rf_text
  accepts_nested_attributes_for :authemps, :allow_destroy => true
  accepts_nested_attributes_for :procedures, :allow_destroy => true

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :form
  attr_accessible :engy_ctrl_pt, :haz_eng_loc, :image, :lo_dev, :resid_engy, :step_num, :valid_zero, :image_cache
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with :name => "un", :password => "password"
end

app/controllers/authemps_controller.rb
class AuthempsController < ApplicationController
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	# GET /clients
  # GET /clients.json
	def index
		@clients = Client.all

		respond_to do |format|
      		format.html # index.html.erb
      		format.json { render json: @clients }
    	end
	end
	# GET /clients/1/
	# GET /clients/1/.json
	def new
		@client = Client.new

		respond_to do |format|
      		format.html # show.html.erb
      		format.json { render json: @client }
   		end
	end
	# DELETE /clients/1/
	# DELETE /clients/1/.json
	def destroy
		@client = Client.find(params[:id])
		@client.destroy

		respond_to do |format|
      		format.js
    	end
	end
	# GET /clients/1
	# GET /clients/1.json
	def show
		@client = Client.find(params[:id])

    	respond_to do |format|
      		format.html # show.html.erb
      		format.json { render json: @client }
   	 	end
  	end
  	# PUT /clients/1
  	# PUT /clients/1.json
  	def create
  		@client = Client.new(params[:client])

    	respond_to do |format|
      		if @client.save
        		format.html { redirect_to @client, notice: 'Client successfully added.' }
        		format.json { render json: @client, status: :created, location: @client }
      		else
        		format.html { render action: "new" }
        		format.json { render json: @client.errors, status: :unprocessable_entity }
      		end
    	end
  	end
  	# GET /clients/1
  	def edit
  		@client = Client.find(params[:id])
  	end
  	# PUT /clients/1
  	# PUT /clients/1.json
  	def update
    	@client = Client.find(params[:id])

    	respond_to do |format|
      		if @client.update_attributes(params[:client])
        		format.html { redirect_to @client, notice: 'Client successfully updated.' }
        		format.json { head :no_content }
     		else
        		format.html { render action: "edit" }
        		format.json { render json: @client.errors, status: :unprocessable_entity }
      		end
    	end
  	end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
	# get client variable
	before_filter :get_client

	def get_client
		@client = Client.find(params[:client_id])
	end
	# GET /forms
  	# GET /forms.json
	def index
		@forms = @client.forms.all

		respond_to do |format|
      		format.html # index.html.erb
      		format.json { render json: @forms }
    	end
	end
	# GET /forms/1/
	# GET /forms/1/.json
	def new
		@form = @client.forms.new

    
    3.times do
      procedure = @form.procedures.build
    end
    3.times do
      authemp = @form.authemps.build
    end

		respond_to do |format|
      		format.html # show.html.erb
      		format.json { render json: @form }
   		end
	end
	# DELETE /forms/1/
	# DELETE /forms/1/.json
	def destroy
		@form = @client.forms.find(params[:id])
		@form.destroy

		respond_to do |format|
      		format.js
    	end
	end
	# GET /forms/1
	# GET /forms/1.json
	def show
		@form = @client.forms.find(params[:id])
    @procedures = @form.procedures.order('step_num ASC')

    	respond_to do |format|
      		format.html # show.html.erb
      		format.json { render json: @form }
   	 	end
  	end
  	# PUT /forms/1
  	# PUT /forms/1.json
  	def create
  		@form = @client.forms.new(params[:form])

    	respond_to do |format|
      		if @form.save
        		format.html { redirect_to @client, notice: 'Lockout Tagout Form successfully added.' }
        		format.json { render json: @client, status: :created, location: @form }
      		else
        		format.html { render action: "new" }
        		format.json { render json: @form.errors, status: :unprocessable_entity }
      		end
    	end
  	end
  	# GET /forms/1
  	def edit
  		@form = @client.forms.find(params[:id])
      @procedures = @form.procedures.order('step_num ASC')
  	end
  	# PUT /forms/1
  	# PUT /forms/1.json
  	def update
    	@form = @client.forms.find(params[:id])

    	respond_to do |format|
      		if @form.update_attributes(params[:form])
        		format.html { redirect_to @client, notice: 'Lockout Tagout Form successfully updated.' }
        		format.json { head :no_content }
     		else
        		format.html { render action: "edit" }
        		format.json { render json: @form.errors, status: :unprocessable_entity }
      		end
    	end
  	end

end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/authemps_helper.rb
module AuthempsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
	def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def check_a_box(bool)
    if bool == false
      image_tag("FALSE_Checkbox.gif")
    else
      image_tag("TRUE_Checkbox.gif")
    end
  end

  def image_check(link)
    if link.blank?

    else
      image_tag(link)
    end
  end

end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<!-- client description form table contains editable fields for:
		- Client Name
		- Client Details
		- Client Location
		- Client Contact -->
	<div class="table">
		<table>
			<tr>
				<th class="top" colspan="2">
					Client Form
				</th>
			</tr>
			<tr>
				<td class="tleft w20">
					Client Name:
				</td>
				<td class="tleft">
					<%= f.text_field :name, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Client Details:
				</td>
				<td class="tleft">
					<%= f.text_area :details, :class=>"area w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Client Location:
				</td>
				<td class="tleft">
					<%= f.text_field :location, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Client Contact:
				</td>
				<td class="tleft">
					<%= f.text_field :contact, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Client Actions:
				</td>
				<!-- client description table contains client information (above) and action buttons -->
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= f.submit 'Save Client Info', :class=>"link2" %></li>
						<li><%= link_to 'Back to Client List', clients_path, :class=>"link2" %></li>
					</ul>
				</td>
			</tr>
		</table>
	</div>

<% end %>

app/views/clients/destroy.js.erb
$('#<%= dom_id(@client)%>').fadeOut();

app/views/clients/edit.html.erb
<%= render 'form' %>

app/views/clients/index.html.erb
<!-- the entire client index table is contained in div w/ class="table" -->
<div class="table">
	<!-- first subtable contains the main header and the column headers -->
	<table>
		<tr>
			<th class="top" colspan="4">
				Compliance Application
			</th>
		</tr>
		<tr>
			<th class="sub tleft w25">
				Client Name:
			</th>
			<th class="sub tleft w25">
				Client Location:
			</th>
			<th class="sub tcenter w20">
				Contact:
			</th>
			<th class="sub tcenter">
				Client Actions:
			</th>
		</tr>
	</table>
	<!-- div_for creates new subtable for each department created -->
	<%= div_for(@clients) do |client| %>
		<!-- each department subtable contains department information and action buttons -->
		<table>
			<tr>
				<td class="tleft w25">
					<%= client.name %>
				</td>
				<td class="tleft w25">
					<%= client.location %>
				</td>
				<td class="tcenter w20">
					<%= client.contact %>
				</td>
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= link_to 'Edit Info', edit_client_path(client), :class=>"link3" %></li>
						<li><%= link_to 'Lockout Tagout Forms', client_path(client), :class=>"link3" %></li>
						<li><%= link_to 'Destroy', client, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class=>"link3" %></li>
					</ul>
				</td>
			</tr>
		</table>
	<% end %>
	<!-- last subtable contains the button to create new departments -->
	<table>
		<tr>
			<td class="tcenter" colspan="4">
				<%= link_to 'Add New Client', new_client_path, :class=>"link1" %>
			</td>
		</tr>
	</table>
</div>

app/views/clients/new.html.erb
<%= render 'form' %>

app/views/clients/show.html.erb
<!-- the entire client description table is contained in div w/ class="table" -->
<div class="table">
	<table>
		<tr>
			<th class="top" colspan="2">
				<%= @client.name %> Client Information
			</th>
		</tr>
		<tr>
			<th class="sub tleft w20">
				Client Name:
			</th>
			<th class="sub tleft">
				<%= @client.name %>
			</th>
		</tr>
		<tr>
			<td class="tleft">
				Client Details:
			</td>
			<td class="tleft">
				<%= @client.details %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Client Location:
			</td>
			<td class="tleft">
				<%= @client.location %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Client Contact:
			</td>
			<td class="tleft">
				<%= @client.contact %>
			</td>
		</tr>
		<tr>
			<td class="tleft">
				Client Actions:
			</td>
			<!-- client description table contains client information (above) and action buttons -->
			<td class="tcenter">
				<ul class="menu w100">
					<li><%= link_to 'Edit Client Info', edit_client_path(@client), :class=>"link2" %></li>
					<li><%= link_to 'Back to Client List', clients_path, :class=>"link2" %></li>
				</ul>
			</td>
		</tr>
	</table>
</div>
<%= render 'forms/index' %>

app/views/forms/_index.html.erb
<!-- the entire task index table is contained in div w/ class="table" -->
<div class="table">
	<!-- first subtable contains the main header and the column headers -->
	<table>
		<tr>
			<th class="top" colspan="4">
				Lockout Tagout Forms for <%= @client.name %> 
			</th>
		</tr>
		<tr>
			<th class="sub tleft w25">
				Equipment ID:
			</th>
			<th class="sub tleft w25">
				Equipment Name:
			</th>
			<th class="sub tcenter">
				Task Actions:
			</th>
		</tr>
	</table>
	<!-- div_for creates new subtable for each task created -->
	<%= div_for(@client.forms) do |form| %>
		<!-- each task subtable contains task information and action buttons -->
		<table>
			<tr>
				<td class="tleft w25">
					<%= form.equip_id %>
				</td>
				<td class="tleft w25">
					<%= form.equip_name %>
				</td>
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= link_to 'Edit Info', edit_client_form_path(@client,form), :class=>"link3" %></li>
						<li><%= link_to 'Show Completed Form', client_form_path(@client, form), :class=>"link3" %></li>
						<li><%= link_to 'Destroy', [@client,form], method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class=>"link3" %></li>
					</ul>
				</td>
			</tr>
		</table>
	<% end %>
	<!-- last subtable contains the button to create new tasks -->
	<table>
		<tr>
			<td class="tcenter" colspan="4">
				<%= link_to 'Create New Lockout Tagout Form', new_client_form_path(@client), :class=>"link1" %>
			</td>
		</tr>
	</table>
</div>

app/views/forms/_loto.html.erb
<%= nested_form_for([@client,@form]) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- COMMENT LATER -->
	<div class="table">
		<table>
			<tr>
				<th class="top" colspan="2">
					Energy Control Procedure
				</th>
			</tr>
			<tr>
				<td class="tleft w20">
					Equipment Name:
				</td>
				<td class="tleft">
					<%= f.text_field :equip_name, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Equipment ID:
				</td>
				<td class="tleft">
					<%= f.text_field :equip_id, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Equipment Location:
				</td>
				<td class="tleft">
					<%= f.text_field :equip_location, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Date of Assessment:
				</td>
				<td class="tleft">
					<%= f.date_select :assess_date, :class=>"field w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Tasks to be Performed:
				</td>
				<td class="tleft">
					<%= f.text_area :tasks_performed, :class=>"area w99" %>
				</td>
			</tr>
			<tr>
				<td class="tleft">
					Persons Performing the Assessment:
				</td>
				<td class="tleft">
					<%= f.text_area :assessor, :class=>"area w99" %>
				</td>
			</tr>
		</table>
		<table>
			<tr>
				<td class="tcenter top" colspan="2">
					Table A - Identification of Hazardous Energies
				</td>
			</tr>
			<tr>
				<td class="w50">
					<table class="checkbox1">
						<tr>
							<td class="tleft">
								<%= f.check_box :elec_highvolt %>
							</td>
							<td class="tleft">
								Electrical - High Voltage (600V or more) <%= f.text_field :highvolt_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :elec_lowvolt %>
							</td>
							<td class="tleft">
								Electrical - Low Voltage (50V - 600V) <%= f.text_field :lowvolt_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :chem_hazmat %>
							</td>
							<td class="tleft">
								Chemicals, Gases - Hazardous Materials <%= f.text_field :hazmat_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :mech %>
							</td>
							<td class="tleft">
								Mechanical - Shearing, pinching, rolling <%= f.text_field :mech_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">	 
								<%= f.check_box :stored_engy %>
							</td>
							<td class="tleft">
								Stored Energy - Springs, capacitors, batteries <%= f.text_field :stored_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :therm_cryo %>
							</td>
							<td class="tleft">
								Thermal - Cryogenics - temp below 32°F/O°C <%= f.text_field :cryo_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :therm_high %>
							</td>
							<td class="tleft">
								Thermal - Temperature above 140°F/60°C <%= f.text_field :high_text, :class => "box" %>
							</td>
						</tr>
					</table>
				</td>
				<td class="w50">
					<table class="checkbox1">
						<tr>
							<td class="tleft">
								<%= f.check_box :press_hyd %>
							</td>
							<td class="tleft"> 
								Pressure - Hydraulic (oil, water) <%= f.text_field :hyd_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :press_pneu %>
							</td>
							<td class="tleft">
								Pressure - Pneumatic (air, gas) <%= f.text_field :pneu_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :vacuum %>
							</td>
							<td class="tleft">
								Vacuum - PRessure @ mTorr <%= f.text_field :vac_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :ion_rad %>
							</td>
							<td class="tleft">
								Ionizing Radiation - X-Ray sources <%= f.text_field :rad_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :non_rad_uv %>
							</td>
							<td class="tleft">
								Non-Ionizing Radiation - UV, IR <%= f.text_field :uv_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :non_rad_rf %>
							</td>
							<td class="tleft">
								Non-Ionizing Radiation - RF, Lasers <%= f.text_field :rf_text, :class => "box" %>
							</td>
						</tr>
						<tr>
							<td class="tleft">
								<%= f.check_box :other %>
							</td>
							<td class="tleft">
								Other: <%= f.text_field :other_text, :class => "box" %>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<table>
				<th class="top" colspan="2">
					Table B: Basic Lockout/Tagout Procedures:
				</th>
				<tr colspan="2"> Review and perform you Lockout/Tagout by following these steps.</tr>
				<tr>
					<td class="tleft sub">Lockout Procedure Steps</td>
					<td class="tleft sub">Procedure To Return Equipment To Operation</td>
				</tr>
				<tr>
					<td class="tleft">
						<ul>
							<li>1.	Read and Understand this Energy Control Procedure</li>
							<li>2.	Get all applicable Lockout and Tagout (LOTO) Devices</li>
							<li>3.	Notify Affected Persons then Initiate Shutdown Sequence according to Table C</li>
							<li>4.	List hazardous energy in Column A (from Table A)</li>
							<li>5.	List energy control point(s) in Column B</li>
							<li>6.	Apply LOTO devices indicated in Column “C”</li>
							<li>7.	Dissipate or release any residual energy per Column “D”</li>
							<li>8.	Validate “zero energy state” per instructions in Column “E”</li>
						</ul>
					</td>
					<td class="tleft">
						<ul>
							<li>1.	Inspect each energy source area and remove all tools, parts, or other items used during the maintenance activity</li>
							<li>2.	Replace all safety devices (covers, guards, interlocks, emergency stops)</li>
							<li>3.	Remove LOTO devices and re-energize equipment</li>
							<li>4.	Test all safety devices for proper operation</li>
							<li>5.	Notify Affected Persons equipment ready for use</li>
						</ul>
					</td>
				</tr>
			</table>
			<table>
				<th class="top" colspan="6">
					Table C: Shutdown Sequence and Specific Procedures
				</th>
				<tr>
					<td class="tleft w10 sub">
							Step #
					</td>
					<td class="tleft w15 sub">
							Hazardous Energy and Locations
					</td>
					<td class="tleft w15 sub">
							Energy Control Points
					</td>
					<td class="tleft w15 sub">
							Lockout Device
					</td>		
					<td class="tleft w15 sub">
							Dissipation or Release of Residual Energies
					</td>	
					<td class="tleft w15 sub">
							Validation of Zero Energy State
					</td>
				</tr>
			</table>
			<%= f.fields_for :procedures, @procedures do |proc| %>
			<table>
				<tr>
					<td class="tleft w10">
						<%= proc.text_field :step_num, :class=>"field w99" %>
					</td>
					<td class="tleft w15">
						<%= proc.text_area :haz_eng_loc, :class=>"area w99" %>
					</td>
					<td class="tleft w15">
						<%= proc.text_area :engy_ctrl_pt, :class=>"area w99" %>
					</td>
					<td class="tleft w15">
						<%= proc.text_area :lo_dev, :class=>"area w99" %>
					</td>
					<td class="tleft w15">
						<%= proc.text_area :resid_engy, :class=>"area w99" %>
					</td>
					<td class="tleft w15">
						<%= proc.text_area :valid_zero, :class=>"area w99" %>
					</td>
				</tr>
				<tr>
					<td class="tleft">
						Image Upload
					</td>
					<td class="tleft" colspan="">
						<%= proc.file_field :image, :class=>"field w99"%>
						<%= proc.hidden_field :image_cache %>
					</td>
				</tr>
				<tr>
					<td class="tcenter w99" colspan="6">
						<%= proc.link_to_remove "Remove this Step" %>
					</td>
				</tr>	
			</table>
			<% end %>
			<table>
				<tr>
					<td class="tcenter w99">
						<%= f.link_to_add "Add a Step", :procedures %>
					</td>
				</tr>
			</table>
			<table>
				<th class="top" colspan="2">
					Table D: Authorized Employees
				</th>
				<tr>
					<td class="tleft w50 sub">
							Name:
					</td>
					<td class="tleft w50 sub">
							Title:
					</td>
				</tr>
			</table>
			<%= f.fields_for :authemps do |ae| %>
				<table>
					<tr> 
						<td class="tleft w50">
							<%= ae.text_field :name, :class=>"area w99" %>
						</td>
						<td class="tleft w50">
							<%= ae.text_field :title, :class=>"area w99" %>
						</td>
					</tr>
					<tr>
						<td class="tcenter w99" colspan="6">
							<%= ae.link_to_remove "Remove this Employee" %>
					</tr>	
				</table>
			<% end %>
			<table>
				<tr>
					<td class="tcenter w99">
						<%= f.link_to_add "Add a Authorized Employee", :authemps %>
					</td>
				</tr>
			</table>
			<table>
				<th>Transfer of the Control of LOTO Devices during Change of Shift:</th>
				<tr><td>If this procedure lasts more than one work shift, the arriving shift employees will apply their locks and tags before the departing shift employees remove their locks and tags. In addition, the arriving shift authorized employee(s) will review and verify that the procedures listed above have been followed and are still in place.</td></tr> 
			<table>
			<tr>
				<td class="tleft">
					Form Actions:
				</td>
				<!-- COMMENT LATER -->
				<td class="tcenter">
					<ul class="menu w100">
						<li><%= f.submit 'Save Form', :class=>"link2" %></li>
						<li><%= link_to 'Back to Form List', client_path(@client) , :class=>"link2" %></li>
					</ul>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/forms/destroy.js.erb
$('#<%= dom_id(@form)%>').fadeOut();

app/views/forms/edit.html.erb
<%= render 'loto' %>

app/views/forms/new.html.erb
<%= render 'loto' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>